[loggers]
keys=root,paramiko,paramiko_transport,netmiko,netmiko_base,netmiko_utilities

[logger_root]
level=NOTSET
handlers=consoleHandler,fileHandler

[logger_paramiko]
level=WARNING
handlers=fileHandler
qualname=paramiko
propagate=0

[logger_paramiko_transport]
level=WARNING
handlers=fileHandler
qualname=paramiko.transport
propagate=0

[logger_netmiko]
level=INFO
handlers=fileHandler
qualname=netmiko
propagate=0

[logger_netmiko_base]
level=DEBUG
handlers=fileHandler
qualname=netmiko.base_connection
propagate=0

[logger_netmiko_utilities]
level=WARNING
handlers=fileHandler
qualname=netmiko.utilities
propagate=0

[formatters]
keys=mainFormatter

[formatter_mainFormatter]
format=%(asctime)s - %(levelname)-8s  %(name)s: %(message)s
datefmt=%Y-%m-%d %H:%M:%S

[handlers]
keys=consoleHandler,fileHandler

[handler_consoleHandler]
class=StreamHandler
level=INFO
formatter=mainFormatter
args=(sys.stdout,)

[handler_fileHandler]
class=FileHandler
level=DEBUG
formatter=mainFormatter
args=("logs/debug.log",)
